sudo: false
language: python
python:
  - 3.4
  - 3.5
  - 3.6

cache:
  pip: true
  directories:
    - node_modules

os:
  #  # The macOS build in travis is really slow.
  #  - osx
  - linux

# Note that in order to run the tests on Linux,
# you need to have a before_install configuration
# to enable Linux to start VS Code from the build.
# ref https://code.visualstudio.com/Docs/extensions/testing-extensions
before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
      sleep 3;
    fi

  - printf '%s\n'
           "$(cat test-requirements.txt requirements.txt)"
           > requirements.txt

jobs:
  include:
    - python: 3.6
      stage: moban
      before_install: false
      install: pip install moban
      script: .ci/check_moban.sh
      after_success: false

script:
  - >
  # https://github.com/coala/coala-bears/issues/1037
  - sed -i.bak '/bears = GitCommitBear/d' .coafile
  # Server side tests.
  - coverage run $(which behave) ./tests/server.features
  - coverage run -a -m unittest discover -s tests

notifications:
  email: false
  webhooks: https://www.travisbuddy.com/
  on_success: never

after_success:
  - codecov
#  # If the build was triggered by a tag, publish the new version
#  - 'if [[ $TRAVIS_TAG == v* ]]; then vsce publish -p $VSCE_TOKEN; fi'
